AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: {% include "_cctmp/class_name.txt" %}

Parameters:

  RailsEnv:
    Type: String
    Default: staging
    AllowedValues:
      - staging
      - production

Resources:

  {% include "_cctmp/class_name.txt" %}Lambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app.handler
      Runtime: ruby2.7
      MemorySize: 512
      Timeout: 30
      Environment:
        Variables:
          RAILS_ENV: !Ref RailsEnv
          RUBYOPT: -W0
      FunctionName: !Sub {% include "_cctmp/dash_name.txt" %}-${RailsEnv}
      Events:
        {% include "_cctmp/class_name.txt" %}HttpApiProxy:
          Type: HttpApi
          Properties:
            ApiId: !Ref {% include "_cctmp/class_name.txt" %}HttpApi
      AutoPublishAlias: live

  {% include "_cctmp/class_name.txt" %}HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref RailsEnv

Outputs:

  {% include "_cctmp/class_name.txt" %}HttpApiUrl:
    Description: Lambda Invoke URL
    Value: !Sub "https://${{ "{" }}{% include "_cctmp/class_name.txt" %}HttpApi}.execute-api.${AWS::Region}.amazonaws.com/${RailsEnv}/"

  {% include "_cctmp/class_name.txt" %}LambdaResourceArn:
    Description: Lambda ARN
    Value: !GetAtt {% include "_cctmp/class_name.txt" %}Lambda.Arn
