version: '3.7'
services:
  {% include "_cctmp/dash_name.txt" %}:
    build:
      context: '.'
      dockerfile: Dockerfile-build
    environment:
      - RAILS_ENV=${RAILS_ENV-development}
      - SAM_CLI_TELEMETRY=0
      - AWS_PROFILE=${AWS_PROFILE-default}
    volumes:
      - ${PWD}:/var/task
      - ${HOME}/.aws:/root/.aws
      - /var/run/docker.sock:/var/run/docker.sock
